[package]
name = "lazy-motd"
version = "1.0.7"
edition = "2024"

[[example]]
name = "demo"
path = "examples/demo.rs"

[dependencies]
chrono = "0.4"
machine-uid = "0.5"
sysinfo = "0.37"
termcolor = "1"